# Generated by Django 6.0.5 on 2026-05-06 21:03

import datetime
import django.db.models.deletion
import users.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_in',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 7, 0, 33, 41, 393387)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 7, 0, 33, 41, 393707)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.ImageField(upload_to=users.functions.get_upload_path_for_profile_image)),
                ('is_primary', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
